### ISSUE TITLE
Explosher show Splash + Direct

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1073]
Often explo hits this combo + e.g. can't hit RM without doing it

**Comment by ElementUser** [comment]
Somewhat related (since I play Explosher sometimes):

On the Build Analyzer page, Explosher doesn't have a `Damage` collapsible element: 

![image](https://user-images.githubusercontent.com/15804376/198847713-ff82a274-ec7f-4e33-91fb-04db804987fd.png)

Should I file a separate task for that?

Also in case the info is needed:
- Direct Hit Damage: 55
- Splash Damage: 35

So Direct + Splash damage hit on a target is 55 + 35 = 90 damage

**Comment by ElementUser** [comment]
Hmm, I noticed it's not always there for the Slosher/bucket weapon class in general (Slosher, Tri-Slosher, Bloblobber, Explosher, Sloshing Machine) :(

**Comment by Sendouc** [comment]
I added those today :) https://github.com/Sendouc/sendou.ink/commit/7af8e7a9dbc2ca7f570e6e294a13885fd999ac67

Going to release tomorrow

**Comment by Sendouc** [comment]
And this particular task is a bit tricky so I will probably figure this myself.
