### ISSUE TITLE
(TO Tools) Form submit fails on iOS 15 but not iOS 16

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1138]
Error: 
![image](https://user-images.githubusercontent.com/38327916/202842173-8fa784f1-9e1f-4e88-8fb5-f11b190b76f4.png)

So iOS 15 is lacking something of the basic form functionality..? What?

Full conversation:

![image](https://user-images.githubusercontent.com/38327916/202842156-283f9c81-6b8f-4b0a-8e67-4c3e60d3b471.png)

**Comment by remmycat** [comment]
So the error seems to be zod saying that the data doesn't match any of the union members we specify for the action.
Trying to reproduce and solve this by installing an iOS 15 simulator via XCode

**Comment by remmycat** [comment]
I was able to reproduce it, seems to be that the `_action` field got submitted twice somehow, and therefore it's not matching the object shape we define. Will check if there is an underlying issue why this is sent twice, or if we just need to adjust the matching here to respect this possibility.

<img width="297" alt="Screenshot 2022-11-19 at 13 50 29" src="https://user-images.githubusercontent.com/3317423/202851782-a07c28b3-c42c-495a-8ebc-3dfe1b1e3650.png">

**Comment by remmycat** [comment]
Alright, it seems like this is a combination bug of Remix form handling with Safari 15 behaviour that wasn't "fixed" on Remix's side, because Safari released a fix in v16 that makes it behave the same as other browsers when firing the submit event.
I'm not too happy about that issue just being dismissed on Remix's side, as Safari 15 is still quite recent. Maybe we could ask for it to be reopened.

https://github.com/remix-run/remix/issues/4023

When switching javascript off (so it's just the native form submit logic), the submit button value gets sent only once.

I think the easiest fix for us would be to just never use the submit button `value` and instead attach it to an `<input type="hidden">`. Though this won't work if we ever want to have multiple submit buttons in a single form.

**Comment by Sendouc** [comment]
Ok nice findings! Yeah I definitely agree with you but maybe it's just easiest for now to tell people that the bug is fixed in iOS 16 🤷 Refactoring to use `<input type="hidden">` is probably also possible but maybe a bit inconvenient. Asking Remix to fix it could be an option also but I wonder if it would be considered...

**Comment by remmycat** [comment]
Ah, I only now saw the longer discussion on why remix didn't include a fix https://github.com/remix-run/remix/pull/4024

Alright, I'm fine with just telling people to upgrade then if they run into this.

But maybe I'll still create a PR for changing to hidden inputs, just for now? It's only 4 or so anyway.

**Comment by Sendouc** [comment]
Yeah it's not a bad idea! I guess then gotta make it so that:

```html
<form>
  <button type="submit" name="_action" value="EDIT_TEAM">
  <button type="submit" name="_action" value="DELETE_TEAM">
</form>
```

becomes

```html
<form>
  <button type="submit" name="_action" value="EDIT_TEAM">
</form>
<form>
  <button type="submit" name="_action" value="DELETE_TEAM">
</form>
```

**Comment by remmycat** [comment]
> Yeah it's not a bad idea! I guess then gotta make it so that:
> 
> ```
> <form>
>   <button type="submit" name="_action" value="EDIT_TEAM">
>   <button type="submit" name="_action" value="DELETE_TEAM">
> </form>
> ```
> 
> becomes
> 
> ```
> <form>
>   <input type="hidden" name="_action" value="EDIT_TEAM">
>   <button type="submit">
> </form>
> <form>
>   <input type="hidden" name="_action" value="DELETE_TEAM">
>   <button type="submit">
> </form>
> ```

Yeah, this wasn't necessary on the TO team page (every form already had it's own submit) but would have been necessary on the badge edit page.

Since that one is probably relevant to much less users and I didn't wanna break anything, I just applied the simple fixes on the TO page. Now everything works using the Safari 15 simulator on that page.
