### ISSUE TITLE
Planner make progress save locally

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1157]
It should save locally to IndexexDB. But if you refresh page all progress is lost. Investigate why and fix.

**Comment by ElementUser** [comment]
I checked just now & it's actually not writing to IndexedDB at all (on any web browsers). It always shows up as empty when viewing the Map Planner on the website.

I did check other TLDraw app websites & they write to IndexedDB (I see entries that update whenever I add/remove a shape, but data exists in IndexedDB even without doing anything in particular)

The data for TLDraw on your website must be writing it to somewhere else & we're unable to view where on our web browser - is there a chance that the data could be written on the Remix server side somehow (even if it's temporary)?

**Comment by Sendouc** [comment]
Hmm no I don't think there is any chance of something like that happening. This is something we are doing wrong with TLDraw.

**Comment by ElementUser** [comment]
Just wanted to add some documentation regarding the original issue (copied from Discord): the fix for this primarily involves just adding an `id` field to the `<Tldraw />` component when using it:

![image](https://user-images.githubusercontent.com/15804376/212572998-2558958d-4776-4a0e-8f2f-d203c0934f9d.png)

![image](https://user-images.githubusercontent.com/15804376/212572971-2488a7a8-6065-4c67-96f6-8e67d106e1d4.png)

An example of this can be found from the Tldraw repo: https://github.com/tldraw/tldraw/blob/main/examples/tldraw-example/src/persisted.tsx

**Comment by ElementUser** [comment]
I think this can be closed now 🙂
