### ISSUE TITLE
Abbreviation search for WeaponCombobox

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1217]

**Comment by 4n1m4t10n** [comment]
i have been working on this, but ive found an issue that might prevent abbreviations:

because we use fuse for fuzzy search, each weapon gets its own label and it does not seem possible to add multiple labels to each weapon. as a result, i believe there is a possible solution we can use here:

-individually add abbreviation words to each weapon label. for example, rn h3's label is "H-3 Nozzlenose D." but to account for abbreviations such as h3d, i believe the best case scenario is to add it for the label to be "H-3 Nozzlenose Dh3d," which would show up using either the name or the abbreviation

**Comment by Sendouc** [comment]
Hey sorry but this solution is not good. It's hacky and messes up with the fuzzy searching for the normal name. I would suggest you look for a solution that is working outside of fuse.js. For example:

1) Go through abbreviations and if exact match found then return that weapon
2) If no matches found then do the behavior that is on the site currently

**Comment by 4n1m4t10n** [comment]
ty for the heads up!! that seems like an option, but if we do that then it means for each abbreviation there will only be one specific option, rather than a range of them with fuzzy. if youre okay with that, ill work on this solution asap

**Comment by Sendouc** [comment]
hmm what about something like this:

```ts
// this in a different file probably somewhere in the in-game-lists module
type WeaponAbbreviationsMap = Map<string, MainWeaponId>
const weaponAbbreviations: WeaponAbbreviationsMap = new Map([
  ["h3d", 311],
  ["somethingelse", 311]
]);

// ...

const abbreviatedMainWeaponId = weaponAbbreviations.get(abbreviation) // abbreviation = user input normalized
if (abbreviatedMainWeaponId) return [abbreviatedMainWeaponId];

// existing fuzzy search logic goes here
```

a bit pseudo-code but hope you get the idea!

**Comment by 4n1m4t10n** [comment]
what exactly is the "abbreviation" equivalent for user input in the combobox file? i have been testing and dont seem to find it in the fuzzy search function

**Comment by Sendouc** [comment]
In this case it would be "query" variable in the `<Combobox />` component

**Comment by 4n1m4t10n** [comment]
would there be issues using the variable outside of the component? i was thinking to create two comboboxes depending on if user input is an abbreviation

**Comment by Sendouc** [comment]
Hmm no I don't think you should create a new component for this. btw if you are newer to React i highly recommend checking out their new docs https://react.dev/ they are excellent to say the least

**Comment by 4n1m4t10n** [comment]
ive done one web app w react so theres definitely more i can learn. tyvm!!! 

also yes its way trickier than i thought too lmao but i really wanna find a way cause the idea is very convenient
