### ISSUE TITLE
Sploosh not visible on team page

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1370]
![image](https://user-images.githubusercontent.com/38327916/236014795-c8017143-7118-4eb4-ba74-520b7ff087ef.png)

Tip: probably has to do with the fact that Sploosh's ID is 0

**Comment by pm-wobbuffet** [comment]
in app\features\team\queries\findByIdentifier.server.ts, you have:
```typescript
weapons: JSON.parse(member.weapons).filter(Boolean),
```
which will filter out sploosh because 0 casts to a falsy Boolean.
You could consider something like this:
```typescript
weapons: JSON.parse(member.weapons).filter((x: any) => { return (x === 0) ? true : Boolean(x)}),
```
which would opt-in any integer 0 values and then fallback to truthy test Boolean() to filter out the remaining nulls. This allows sploosh through on my local copy:
![image](https://user-images.githubusercontent.com/6683213/236035430-eee37a38-b9c1-4b51-bbeb-378067705250.png)
