### ISSUE TITLE
Join multiple teams

### ISSUE THREAD

**Issue by ximk** [Sendouc/sendou.ink#1763]
This would mainly be to give coaches the ability to appear on the team page of the team(s) they are coaching on top of the team they are already playing for (if they are on a team), but could also be applicable to players who are on two teams at once (maybe one for competitive and one for their collegiate team).

Squishy in the Discord said they'd be willing to work on it if this sounds like a good idea.
![image](https://github.com/Sendouc/sendou.ink/assets/104683822/49eaeda2-d868-464a-a817-1620425facf9)

**Comment by Sendouc** [comment]
Sure it's a commonly requested feature. But it's somewhat complex feature so I'd first recommend starting with listing out all the changes you think you need to make and probably I can point out any potential shortcomings.

**Comment by timwalter27** [comment]
Hi! I am squishy.
While I haven't worked in this codebase before, I work partially with typescript and html at my part-time job.
Let me know if you want me to dive into the codebase for more specifics.

First of, some things to brainstorm:

- Do we want to differentiate between "kinds" of teams? I was thinking of introducing special team designations in the form of an `enum` in order to differentiate between a regular competitive team and a special one. That would be regular, collegiate, special event (like national teams that only play for national events), LAN, school, and what else we could come up with. Having these in a centralized `enum` will also make it easier to add to it later on with people's requests.
- Do we want players to be able to join two "regular teams"? Or do we want players to only join a second team if it is for the special purposes? I think here it would be best to just say one can join any kind of team as a second option, since we also want coaches to "join" a second team. A coach would then have to be designated so by the captain on the roster page of the team. Being a coach of a team would also add a little icon as I discuss in the below bullet point.
- Do we want little stickers/icons next to team names on people's profiles if it is a "special" team? It would be about the size as the red bubble here:
<img width="285" alt="image" src="https://github.com/Sendouc/sendou.ink/assets/135046574/e871b70d-d88d-4300-8c8b-4df9e0b40125">

Right now I was thinking about this very vague flow of changes I would implement, but this will change based on what we decide on the above questions:

- Change the currently hardcoded value of maximum number of allowed teams to 2
- The team creation page will change. I would add a dropdown in order to select what "type" of team one is joining. The default value here would be the regular option which is what will apply to 90% or more of teams (we could come up with the least confusing name for this option, such as "regular competitive"). The dropdown would then also contain "collegiate, special event, etc"
- The rest of the logic would pretty much remain the same, the only major change is changing the maximum allowable number of team to be 2. I think to discuss the stream of logic further we need to answer the initial questions above.

**Comment by Sendouc** [comment]
Hmm based on your ideas here is how I think it could work:

- I would not do the enums idea upfront. It's something that could happen in the future but right now I don't see it bringing enough value.
- Each user has one "main team" and arbitrary number of "secondary teams" represented by a new field in `AllTeamMember` table (integer, default 1)
- Main team can be selected via new select on the user profile (like fav badge)
- On user profile main team is shown by default but if you have secondary teams then after (where you circled red) could be +1,+2,+3,+4 or whatever and if you click it, it opens a Popover which shows all of them
- Check how `TeamMember` is implemented as a view currently. Maybe we should modify that view to also include the "is main team check". This would be good because then the assumption that one member has one team would stay true and you don't have to check every single place where it's used to make sure it can handle many teams. Then some new view ("TeamMemberIncSecondary" or whatever) that also includes the "secondary teams". Depending on the context you choose which you join with.
