### ISSUE TITLE
Upgrade @tldraw/tldraw to latest

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1853]
I get this error when trying to set background image after upgrade:

![image](https://github.com/user-attachments/assets/3744aaf8-b52c-469b-aa9f-06c7ac223107)

Are we doing something wrong?

**Comment by ElementUser** [comment]
@Sendouc I found the issue =)

I was reading through the tldraw 2.4.0 release notes (since it was the most recent major release since 2.3.x) & going through each point one-by-one and seeing if your application has anything from there: https://github.com/tldraw/tldraw/releases/tag/v2.4.0

Turns out that it does!

> The fileSize property of TLImageAsset and TLVideoAsset is now optional. 

I removed that field from the appropriate line & tested it locally, the issue is fixed. I will submit a Pull Request very soon! =)
