### ISSUE TITLE
Special characters not shown correctly in delete build popup

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#994]
Why shows correctly in build title but not delete build modal?

Example character: `/`

<img width="487" alt="image" src="https://user-images.githubusercontent.com/38327916/193930152-0621c508-09ed-4e80-8f2c-bc257d674f8d.png">

<img width="652" alt="image" src="https://user-images.githubusercontent.com/38327916/193930235-450848c7-ef78-4656-ab79-2944892906df.png">

**Comment by remmycat** [comment]
Confirmed that this is due to [i18next escaping translation interpolation values](https://www.i18next.com/translation-function/interpolation#unescape). When setting `interpolation.escapeValue: false` in the config this issue does not occur.

As far as I know the HTML entities that got generated "don't work", because we write the resulting string into a variable.
This variable is then inserted into a JSX tree later on, and the content gets inserted into the DOM by React as a text node, which is it's one form of escaping if you will.
If I remember correctly, React only supports HTML entities when writing them directly into the JSX (not via a string variable), or by using the `dangerouslySetInnerHTML` API.

The only affected characters should be `<`, `/`, and `>`.

Possible ways to move forward I see:
- Evaluate if the i18next library is generally not used in a way where there is a danger of XSS attacks and turning this off in the global i18next config.
- Evaluate if this specific case can not lead to an XSS attack and if it cannot, [turn escaping off for this specific translation](https://www.i18next.com/translation-function/interpolation#unescape).
- Do further research to find out if there are other ways to circumvent this issues, e.g. by searching through issues in the i18next repo.
- Accept that `<`, `/`, and `>` will look broken sometimes.

**Comment by Sendouc** [comment]
Okay interesting. Thanks for a good reply. Idea:

I wonder if it would be a viable solution to let i18next/React do the escaping then call some utility function on the results that is basically doing a bunch of replaces to make `'`, `/` etc look as they should again.

Otherwise it can be a tricky problem as for example in this case just using `dangerouslySetInnerHTML` will lead to XSS as the title is set by user.

**Comment by remmycat** [comment]
I believe in this example just skipping the escaping i18next is doing is perfectly safe, as react escapes strings anyway (when not using `dangerouslySetInnerHTML`). Otherwise we would also have an issue everywhere whereever the text is not broken at the moment 🙂 

This could also be done at specific callsite. This works fine for the specific issue shown above:
```typescript
t("builds:deleteConfirm", { title, interpolation: { escapeValue: false } })`
```

**Comment by Sendouc** [comment]
Ah yeah of course. Then I think it should be enabled globally, right? Since I don't recall ever having to use dangerouslySetInnerHTML in this project.

**Comment by remmycat** [comment]
Yes I believe doing so is fine in a react project, I think devs should really sure about setting `dangerouslySetInnerHTML` or other kinds of HTML injection from user input anyway and not expect the translation library to handle this for them.

I found that the FAQ is actually using `dangerouslySetInnerHTML` with the i18next translations, but there's no interpolation happening:

```tsx
<p
  dangerouslySetInnerHTML={{
    __html: t(`faq:a${questionNumber}` as any),
  }}
/>
```

**Comment by remmycat** [comment]
I created a PR for deactivating this behaviour and fixing this issue -> #1012
